### ISSUE TITLE
automaticallyRecycleParticleSystems is true but there is no ParticleSystem on this GameObject!

### ISSUE THREAD

**Issue by justinwasilenko** [prime31/RecyclerKit#10]
I added a Prefab that has 2 particle systems as childeren inside the prefab. But I always get this error message when I enable RecycleparticleSys. Would be nice to detech Child particle systems and not add them separately.

automaticallyRecycleParticleSystems is true but there is no ParticleSystem on this GameObject!
UnityEngine.Debug:LogError(Object)
TrashManRecycleBin:spawn() (at Assets/Scripts/TrashManRecycleBin.cs:192)
TrashMan:spawn(Int32, Vector3, Quaternion) (at Assets/Scripts/TrashMan.cs:136)
TrashMan:spawn(GameObject, Vector3, Quaternion) (at Assets/Scripts/TrashMan.cs:227)

**Comment by prime31** [comment]
Particle systems as subobjects are not yet supported. You should be able to add it pretty easily though if you need it ASAP by just looking at the current code that deals with a single particle system. 

Mike


On Jun 4, 2015, at 6:07 AM, Justin Wasilenko <notifications@github.com> wrote:

I added a Prefab that has 2 particle systems as childeren inside the prefab. But I always get this error message when I enable RecycleparticleSys. Would be nice to detech Child particle systems and not add them separately.

automaticallyRecycleParticleSystems is true but there is no ParticleSystem on this GameObject!
UnityEngine.Debug:LogError(Object)
TrashManRecycleBin:spawn() (at Assets/Scripts/TrashManRecycleBin.cs:192)
TrashMan:spawn(Int32, Vector3, Quaternion) (at Assets/Scripts/TrashMan.cs:136)
TrashMan:spawn(GameObject, Vector3, Quaternion) (at Assets/Scripts/TrashMan.cs:227)

**Comment by justinwasilenko** [comment]
ok thanks, don't have the time to do it just now, but hope soon. Would be a nice feature.
