### ISSUE TITLE
Objects not Despawning after delay.

### ISSUE THREAD

**Issue by justinwasilenko** [prime31/RecyclerKit#11]
Using:
        TrashMan.despawnAfterDelay( gameObject, lifetime );

Sometimes it works, other times it doesn't. I can't locate the issue reading through the code. Sorry can't be more helpful, not sure what to look for as to why it doesn't despawn. Using Unity 5.2.

**Comment by WhiteNoise** [comment]
Also having this issue.

**Comment by code45709** [comment]
I'm also having the same issue. Also just using despawn doesn't work for me either.

**Comment by prime31** [comment]
I still can't reproduce this. Using the included demo scene pressing the "Spawn Cube" button results in the cube being created then recycled after a delay.

Have you tried setting a breakpoint in the internalDespawnAfterDelay where the object is recycled?

**Comment by code45709** [comment]
Hi,

In unity 5.3.4 if relevant. 

So on a ui text prefab. I have

void Update ()
{
If (timeToReturn <= 0)
{
ActiveNow = true;
If (ActiveNow == true)
{
TrashMan.despawn (go:gameObject);
Print ("code executed");
}
}

**Comment by code45709** [comment]
Oops doing this on phone, not to well. I missed a }.

It doesn't print the line. On the delay I kept getting in the console Trying to Invoke delayDespawn. When I tried using it that way to see if it would yield results. In the delay in seconds I have declared it to be 2f. That didn't work.

Thanks.

**Comment by dgreene1** [comment]
subscribed

**Comment by curiousbrandon** [comment]
I found that if I use despawnAfterDelay on the spawned object itself, it wouldn't work. However if I have it on the object that spawns it, it works fine. Probably obvious but thought I'd comment.
