### ISSUE TITLE
Your license seems to be more restrictive than you want

### ISSUE THREAD

**Issue by darkhog** [prime31/RecyclerKit#14]
Unless I'm wrong about your intentions, you seem to not want this pooler to be sold as part of separate asset/kit. BUT CC-by-nc-sa also prevents its usage in any commercial game whatsoever. Either you should get some lawyer to write you license that actually says what you want (expensive) or get some other license that actually lines up with what you want.

Also please note that CC license seems to not be very good for code according to Creative Commons themselves. I disagree, but "nc" part of the license you're using makes me unable to utilize it in the game I'm working on, even though the code's quality seems to be great and it's very easy to use..

**Comment by prime31** [comment]
Anyone can use RecyclerKit (or any of my *Kit code) in any game commercial or not with no attribution required. The plain text after the license reads as follows:

> You are free to use RecyclerKit in any and all games that you make. You cannot sell RecyclerKit directly or as part of a larger game asset.

I have spoken to a lawyer and they said the plain text addendum would hold up fine. I personally don't have any intention to spend money on getting a specific license written just for my open source code. I've got plenty humongous companies using the code and if they are happy with the license + addendum as is then all should be well.
