### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by andybak** [prime31/RecyclerKit#15]
> Attribution-NonCommercial-ShareAlike 3.0 

and

> You are free to use RecyclerKit in any and all games that you make. You cannot sell RecyclerKit directly or as part of a larger game asset.

That isn't the same as my understanding of NC - you intend to allow use in commercial games as long as the asset isn't sold - but that distinction isn't part of the CC-NC licence terms. Unless I've misunderstood somewhere?

(CC licences are tricky for code and CC themselves advise against it: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software )

Anyway - sorry to be the licence geek and thanks for offering this to the community in any form!

**Comment by Chillu1** [comment]
Same "problem" here. Wanted to use this project for my own "soon to be commercial" game. But I simply can't because of the license issue.

Even though it mentions that it can be used in "any and all games", the license says otherwise (which is what matters).
Switching the license would be ideal.
