### ISSUE TITLE
Issues on PC standalone

### ISSUE THREAD

**Issue by iainlobb** [prime31/RecyclerKit#7]
Using the main branch, on a Windows standalone .exe I get "attempted to spawn go XXX but there is no recycle bin setup for it. Falling back to Instantiate" any time I try to spawn an object. Works in the editor so my only guess would be that the instance id is different on the build?

**Comment by Hanox** [comment]
Had the same issue on OSX standalone. I use this workaround: Checking "Persist Between Scenes" on both TrashMan and the Recycle Bins fixed it for me although the build settings only contained one scene.

**Comment by trantung998** [comment]
Same issues here
